kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume-local
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # CHANGE ME
    path: "/tmp/volume-local"
