apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: nginx-proxy-deploy
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: nginx-proxy
  spec:
   containers:
   - name: nginx-proxy
     image: nginx:alpine
     ports:
     - containerPort: 443
     resources:
      limits:
       memory: 64Mi
     volumeMounts:
     - mountPath: /usr/share/nginx/html/
       name: nginxproxy
     - mountPath: /etc/nginx/
       name: nginxconf
     commond:
       
   volumes:
   - name: nginxproxy
     hostPath:
      path: /srv/ibas/nginx-proxy/html/
   - name: nginxconf
     hostPath:
      path:/srv/ibas/nginx-proxy/conf/
---
apiVersion: v1
kind: Service
metadata:
 name: nginx-proxy
spec:
 type: NodePort
 ports:
 - port: 443
   nodePort: 30001
 selector:
  app: nginx-proxy
