apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: nginx-proxy-deploy
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: nginx-proxy
  spec:
   containers:
   - name: nginx-proxy
     image: nginx:alpine
     ports:
     - containerPort: 80
     resources:
      limits:
       memory: 64Mi
     volumeMounts:
     - mountPath: /usr/share/nginx/html/
       name: nginxproxy
   volumes:
   - name: nginxproxy
     hostPath:
      path: /srv/ibas/nginx-proxy/
