apiVersion: v1
kind: ReplicationController
metadata:
 name: nginx-proxy-rc
spec:
 replicas: 1
 selector:
  name: nginx-proxy
 template:
  metadata:
   labels:
    name: nginx-proxy
  spec:
   containers:
   - name: nginx-proxy
     image: nginx:alpine
     ports:
     - containerPort: 80