apiVersion: extensions/v1beta1
status:
  loadBalancer:
    ingress:
      - ip: 47.95.97.32
kind: Ingress
metadata:
  uid: 8e8687ab-626f-11e8-94f9-00163e10b5d1
  resourceVersion: '863616'
  name: app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3000'
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '1200'
    ingress.kubernetes.io/client-body-buffer-size: 200m
    nginx.ingress.kubernetes.io/proxy-send-timeout: '2400'
    nginx.ingress.kubernetes.io/keepalive-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
  creationTimestamp: '2018-05-28T12:06:30Z'
  selfLink: /apis/extensions/v1beta1/namespaces/deploy/ingresses/app
  generation: 8
  namespace: deploy
spec:
  tls:
    - hosts:
        - app.avacloud.com.cn
        - wechat.avacloud.com.cn
      secretName: app-tls
  rules:
    - host: app.avacloud.com.cn
      http:
        paths:
          - backend:
              servicePort: 80
              serviceName: nginx-svc
            path: /
    - host: wechat.avacloud.com.cn
      http:
        paths:
          - backend:
              servicePort: 80
              serviceName: nginx-svc
            path: /

