apiVersion: v1
kind: ReplicationController
metadata:
  name: c01-01-rc
spec:
  replicas: 1
  selector:
   app: c01-01-pod
  template:
    metadata:
      labels:
        app: c01-01-pod
    spec:
      containers:
        - name: c01-01-web
          image: docker.avacloud.com.cn/colorcoding/nginx:C01-01
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 64Mi
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx
            - mountPath: /etc/localtime
              name: time
        - name: c01-01-tomcat
          image: docker.avacloud.com.cn/colorcoding/tomcat:C01-01
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
          volumeMounts:
            - mountPath: /user/local/tomcat/ibas/conf/
              name: tomcat
            - mountPath: /usr/local/tomcat/ibas/data/
              name: ibasdata
            - mountPath: /etc/localtime
              name: time
      volumes:
        - name: nginx
          hostPath:
            path: /srv/ibas/nginx/c01-01/nginx.conf
        - name: tomcat
          hostPath:
            path: /srv/ibas/tomcat/c01-01/conf/
        - name: ibasdata
          hostPath:
            path: /srv/ibas/tomcat/c01-01/data/
        - name: time
          hostPath:
            path: /etc/localtime