apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: c02-02-deploy
  namespace: deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: c02-02-deploy
    spec:
      containers:
      - name: c02-02-tomcat
        image: docker.avacloud.com.cn/colorcoding/tomcat:c01-01
        ports:
        - containerPort: 8080
        resources:
         limits:
          memory: 512Mi
        env:
        - name: JAVA_OPTS
          value: "-Xmx512m"
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
        - mountPath: /usr/local/tomcat/ibas/conf/
          name: ibasconf
        - mountPath: /usr/local/tomcat/ibas/data/
          name: ibasdata
      - name: c02-02-web
        image: docker.avacloud.com.cn/colorcoding/nginx:c01-01
        ports:
        - containerPort: 80
        resources:
         limits:
          memory: 64Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
        - mountPath: /etc/nginx/nginx.conf
          name: nginx
        - mountPath: /usr/share/nginx/webapps/root/openui5/loader.js
          name: loader
      volumes:
       - name: time
         hostPath:
          path: /etc/localtime
       - name: ibasconf
         hostPath:
          path: /srv/ibas/tomcat/c02-02/conf/
       - name: ibasdata
         hostPath:
          path: /srv/ibas/tomcat/c02-02/data/
       - name: nginx
         hostPath:
          path: /srv/ibas/nginx/c02-02/nginx.conf
       - name: loader
         hostPath:
          path: /srv/ibas/nginx/loader.js
---
#------------------------------------------------#
apiVersion: v1
kind: Service
metadata:
 name: c02-02-web
 namespace: deploy
 labels:
   name: c02-02-web
spec:
 type: NodePort
 ports:
 - port: 80
   nodePort: 30004
 selector:
  app: c02-02-deploy
          