apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: c02-02-deploy
  namespace: deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: c02-02-deploy
    spec:
      containers:
      - name: c02-02-tomcat
        image: docker.avacloud.com.cn/colorcoding/tomcat:c01-01
        ports:
        - containerPort: 8080
        resources:
         limits:
          memory: 512Mi
        env:
        - name: JAVA_OPTS
          value: "-Xmx512m"
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
        - mountPath: /usr/local/tomcat/ibas/
          name: ibas
      - name: c02-02-web
        image: docker.avacloud.com.cn/colorcoding/nginx:c01-01
        ports:
        - containerPort: 80
        resources:
         limits:
          memory: 64Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
      - name: c02-02-data
        image: docker.avacloud.com.cn/colorcoding/data:ibas-alpine
        resources:
         limits:
          memory: 64Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
        - mountPath: /usr/share/ibas/
          name: ibas
      volumes:
       - name: time
         hostPath:
          path: /etc/localtime
       - name: ibas
         hostPath:
          path: /srv/ibas/tomcat/c02-02/ibas/
---
#------------------------------------------------#
apiVersion: v1
kind: Service
metadata:
 name: c02-02-web
 namespace: deploy
 labels:
   name: c02-02-web
spec:
 type: NodePort
 ports:
 - port: 80
   nodePort: 30004
 selector:
  app: c02-02-deploy
