apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ibas-platform-deploy
  namespace: ibas-platform
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ibas-platform-deploy
    spec:
      containers:
      - name: ibas-platform-tomcat
        image: docker.avacloud.com.cn/colorcoding/tomcat:ibas-platform
        ports:
        - containerPort: 8080
        resources:
         limits:
          memory: 512Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
        - mountPath: /usr/local/tomcat/ibas/
          name: data
      - name: ibas-platform-web
        image: docker.avacloud.com.cn/colorcoding/nginx:ibas-platform
        ports:
        - containerPort: 80
        resources:
         limits:
          memory: 64Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
      - name: ibas-platform-data
        image: docker.avacloud.com.cn/colorcoding/data:ibas-alpine
        resources:
         limits:
          memory: 64Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
        - mountPath: /usr/share/ibas/
          name: data
      volumes:
       - name: time
         hostPath:
          path: /etc/localtime
       - name: data
         hostPath:
          path: /srv/ibas/tomcat/ibas-platform/ibas/
---
#------------------------------------------------#
apiVersion: v1
kind: Service
metadata:
 name: ibas-platform-web
 namespace: ibas-platform
 labels:
   name: ibas-platform-web
spec:
 type: NodePort
 ports:
 - port: 80
   nodePort: 32000
 selector:
  app: ibas-platform-deploy
          