apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: c01-01-web-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: c01-01-web-deploy
    spec:
      containers:
       - name: c01-01-web
         image: docker.avacloud.com.cn/colorcoding/nginx:C01-01
         ports:
          - containerPort: 80
         resources:
          limits:
           memory: 64Mi
         volumeMounts:
            - mountPath: /etc/localtime
              name: time
            - mountPath: /etc/nginx/nginx.conf
              name: nginx
            - mountPath: /usr/share/nginx/webapps/root/openui5/loader.js
              name: loader
      volumes:
       - name: time
         hostPath:
          path: /etc/localtime
       - name: nginx
         hostPath:
          path: /srv/ibas/nginx/c01-01/nginx.conf
       - name: loader
         hostPath:
          path: /srv/ibas/nginx/loader.js
---
#------------------------------------------------#
apiVersion: v1
kind: Service
metadata:
 name: c01-01-web
 labels:
   name: c01-01-web
spec:
 type: NodePort
 ports:
 - port: 80
   nodePort: 30003
 selector:
  app: c01-01-web-deploy
