apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: c02-01-web-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: c02-01-web-deploy
    spec:
      containers:
       - name: c02-01-web
         image: docker.avacloud.com.cn/colorcoding/nginx:C01-01
         ports:
          - containerPort: 80
         resources:
          limits:
           memory: 64Mi
         volumeMounts:
            - mountPath: /etc/localtime
              name: time
            - mountPath: /etc/nginx/nginx.conf
              name: nginx
      volumes:
       - name: time
         hostPath:
          path: /etc/localtime
       - name: nginx
         hostPath:
          path: /srv/ibas/nginx/c02-01/nginx.conf
