apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test-deploy
  namespace: deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      containers:  
      - name: c01-01-data
        image: docker.avacloud.com.cn/avacloud/ibas-data:ibas-data-alpine
        resources:
         limits:
          memory: 64Mi
        volumeMounts:
        - mountPath: /home/ibas/
          name: ibasdata  
      volumes:
       - name: ibasdata
         hostPath:
          path: /srv/ibas/customers/c01-01/tomcat/

