apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: c01-01-deploy
  namespace: deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: c01-01-deploy
    spec:
      containers:
      - name: c01-01-tomcat
        image: docker.avacloud.com.cn/colorcoding/tomcat:t01-01
        ports:
        - containerPort: 8080
        resources:
         limits:
          memory: 512Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
        - mountPath: /usr/local/tomcat/ibas/
          name: ibasdata
     - name: c01-01-web
       image: docker.avacloud.com.cn/colorcoding/nginx:t01-01
       ports:
       - containerPort: 80
       resources:
        limits:
         memory: 64Mi
       volumeMounts:
       - mountPath: /etc/localtime
         name: time
       - mountPath: /etc/nginx/nginx.conf
         name: nginx-conf  
     - name: c01-01-web
       image: docker.avacloud.com.cn/colorcoding/ibas-data:ibas-data
       resources:
        limits:
         memory: 64Mi
       volumeMounts:
       - mountPath: /etc/localtime
         name: time
       - mountPath: /etc/nginx/nginx.conf
         name: nginx-conf  
      volumes:
       - name: time
         hostPath:
          path: /etc/localtime
       - name: nginx-conf
         hostPath:
          path: /srv/ibas/customers/c01-01/nginx/
       - name: ibasdata
         hostPath:
          path: /srv/ibas/customers/c01-01/tomcat/
---
#----------------------------------------------#
apiVersion: v1
kind: Service
metadata:
 name: c01-01-service
 namespace: deploy
 labels:
   name: c01-01-service
spec:
 ports:
 - port: 8080
   targetPort: 8080
 selector:
  app: c01-01-deploy
          